language: objective-c
osx_image: xcode9.2
script:
  - xcodebuild -scheme IBAnalyzer -workspace IBAnalyzer.xcworkspace
  - xcodebuild test -scheme IBAnalyzer -workspace IBAnalyzer.xcworkspace
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'IBAnalyzer'

